/* Copyright (c) 2009 Andrea Agosti
 * 
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/* Project Euler - http://projecteuler.net
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not 
 * exceed four million.
 */

#include <stdio.h>
#include <stdint.h>

#define MAX 4000000

int main()
{
  uint32_t result = 0;
  uint32_t ancestor = 0;
  uint32_t tmp = 0;
  uint32_t current = 2;

  /* Only Fib (3k) are even, with k natural integer and
   * Fib (3k) = 4 * Fib (3 (k - 1)) + Fib (3 (k - 2))
   * so we can evaluate only odd numbers:
   * Fib (3 * 0) = 0
   * Fib (3 * 1) = 2
   * Fib (3 * 2) = 8
   * ...
   * and using that we don't even need to track k, we need only
   * the previous 2 even numbers
   */
  while (current < MAX)
    {
      tmp = current;
      result += current;
      /* new Fib (3k) */
      current = (current * 4) + ancestor;
      ancestor = tmp;
    }

  printf ("%d\n", result);

  return 0;
}
